set_property IOSTANDARD LVCMOS18 [get_ports {Q[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Q[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Q[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Q[0]}]
set_property PACKAGE_PIN F15 [get_ports {Q[3]}]
set_property PACKAGE_PIN F13 [get_ports {Q[2]}]
set_property PACKAGE_PIN F14 [get_ports {Q[1]}]
set_property PACKAGE_PIN F16 [get_ports {Q[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports rst]
set_property IOSTANDARD LVCMOS18 [get_ports shr]
set_property IOSTANDARD LVCMOS18 [get_ports shr_in]
set_property PACKAGE_PIN J4 [get_ports clk]
set_property PACKAGE_PIN L3 [get_ports rst]
set_property PACKAGE_PIN K3 [get_ports shr]
set_property PACKAGE_PIN M2 [get_ports shr_in]

set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells <cellname>]]



set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk_IBUF}]

set_property IOSTANDARD LVCMOS18 [get_ports {ss[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ss[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ss[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ss[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ss[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ss[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ss[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports up]
set_property PACKAGE_PIN D20 [get_ports {ss[6]}]
set_property PACKAGE_PIN C20 [get_ports {ss[5]}]
set_property PACKAGE_PIN C22 [get_ports {ss[4]}]
set_property PACKAGE_PIN B22 [get_ports {ss[3]}]
set_property PACKAGE_PIN B21 [get_ports {ss[2]}]
set_property PACKAGE_PIN A21 [get_ports {ss[1]}]
set_property PACKAGE_PIN E22 [get_ports {ss[0]}]
set_property PACKAGE_PIN L3 [get_ports up]

set_property PACKAGE_PIN E14 [get_ports digit]
set_property IOSTANDARD LVCMOS18 [get_ports digit]
