set_property PACKAGE_PIN F15 [get_ports e]
set_property PACKAGE_PIN F13 [get_ports f]
set_property PACKAGE_PIN F14 [get_ports g]
set_property PACKAGE_PIN J4 [get_ports a]
set_property PACKAGE_PIN L3 [get_ports b]
set_property PACKAGE_PIN K3 [get_ports c]
set_property PACKAGE_PIN M2 [get_ports d]

set_property IOSTANDARD LVCMOS18 [get_ports a]
set_property IOSTANDARD LVCMOS18 [get_ports b]
set_property IOSTANDARD LVCMOS18 [get_ports c]
set_property IOSTANDARD LVCMOS18 [get_ports d]
set_property IOSTANDARD LVCMOS18 [get_ports e]
set_property IOSTANDARD LVCMOS18 [get_ports f]
set_property IOSTANDARD LVCMOS18 [get_ports g]
